/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as R3dImport } from './routes/3d'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const R3dRoute = R3dImport.update({
  id: '/3d',
  path: '/3d',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/3d': {
      id: '/3d'
      path: '/3d'
      fullPath: '/3d'
      preLoaderRoute: typeof R3dImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/3d': typeof R3dRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/3d': typeof R3dRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/3d': typeof R3dRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/3d'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/3d'
  id: '__root__' | '/' | '/3d'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R3dRoute: typeof R3dRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R3dRoute: R3dRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/3d"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/3d": {
      "filePath": "3d.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
